# Generated by Django 3.2 on 2021-04-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Movie name')),
                ('rating', models.CharField(blank=True, max_length=255, verbose_name='Movie rating')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Movie description')),
                ('release_date', models.DateField(blank=True, max_length=255, verbose_name='Movie release date')),
                ('duration', models.CharField(blank=True, max_length=255, verbose_name='Movie duration')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
